[global]
dataFrameSerialization = "legacy"

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[server]
runOnSave = true
allowRunOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"