# Streamlit Secrets Template
# Copy your actual secrets here or use environment variables

[google]
api_key = "your_google_api_key_here"

[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
username = "your_email@gmail.com"
password = "your_app_password_here"
from_email = "your_email@gmail.com"

[app]
company_name = "Your Company Name"
database_path = "resume_matcher.db"